name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make pack

    - name: Set Tag and Release
      run: echo "::set-env name=DATE::$(date +%Y-%m-%d)" 
       
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{env.DATE}}
        release_name: Ogen Tools ${{env.DATE}}
        draft: false
        prerelease: false

    - name: Upload Assets
      uses: axel1200/release-asset-action@v1
      with:
       pattern: "*.tar.gz"
       github-token: ${{ secrets.GITHUB_TOKEN }}
       release-url: ${{ steps.create_release.outputs.upload_url }}
